### ISSUE TITLE
Use vue components instead of one big component

### ISSUE THREAD

**Issue by alvarosacari** [Devpaz/image-vue#1]
## Description

- podria componentizar los elementos visibles en lugar de usar un solo componente

## Example

![image](https://user-images.githubusercontent.com/8761785/222852395-c00b02c8-c121-4e57-9728-f33583a5b856.png)

**Comment by Devpaz** [comment]
se agrego los componentes recomendados.
![image](https://user-images.githubusercontent.com/5315991/222916781-5edd4d9d-17ec-410a-8b45-ed81c1e87d0a.png)

**Comment by Devpaz** [comment]
Observaciones subsanadas
